apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-frontend
  name: project-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-frontend
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
      - image: public.ecr.aws/i5a7b8h3/nti-project-frontend:v2.0
        name: project-frontend
        env:
        - name: REACT_APP_API_URL
          value: http://ace729b33e53d4182b3b2e8a48cff00f-2054759395.us-east-1.elb.amazonaws.com/api
