name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch (or any branch you prefer)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mosama25
        password: Hamada2510

    - name: Build and push Docker image
      run: |
        docker build -t mosama25/nti-web-app:latest ./frontend
        docker push mosama25/nti-web-app:latest
